GET https://example.com/
Host: example.com
        User-Agent: curl/7.68.0

##### Another Request

POST        https://example.com/upload
Content-Type:        application/json
    Authorization:   Bearer some_token

{"file": "image.png"


}